# Generated by Django 5.1.3 on 2025-01-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musico", "0003_likedislike"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="album_covers/"),
        ),
    ]
